### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by ArtskydJ**
Added some basic tests using [`tape`](https://github.com/substack/tape).

Right now they're passing except for the "saved" event doesn't seem to fire. (Line 38, test/test-transfer.js)

### CODE REVIEW

**Comment by ArtskydJ** [comment]
If you run `npm test`, this will:

1. browserify `test/serve/browser-file-transfer.js` and save it as `bundle.js`
2. the `test/test-serves-client-js.js` file will be run
  - tests `SocketIOFileUpload.listen(server)` and `SocketIOFileUpload.router`...  
...asserts that `siofu/client.js` is served.
3. the `test/test-transfer.js` file will be run
  - creates a static file/socket.io server with `test/serve` as the root
  - asserts that events are fired on the server
  - spawns chrome, pointed at `localhost/index.html`...  
...this will load the browserified `test/serve/browser-file-transfer.js` file (a.k.a. `bundle.js`) which starts a file upload, and asserts that certain events are fired.

**Comment by ArtskydJ** [comment]
@vote539 thoughts?

**Comment by vote539** [comment]
Thanks for the contribution!  The reason the "saved" event didn't fire was because you never set the "uploader.dir" field.  I also was unable to run the tests on my computer at first because ports 80 and 3000 were in use by other programs, so I added logic for the test to try a few different port numbers.

**Comment by ArtskydJ** [comment]
Cool, thanks!

**Pull request merged**
