### PR TITLE
Siofu progress

### PR DESCRIPTION
**Pull request by MaffooBristol**
Hello, so as mentioned in the other issue on this repo, I've made some *progress* (ho ho ho) with getting the uploads to work in chunks. From my preliminary testing, it seems to be working fine though but it needs reviewing!

Apologies for committing in formatting changes too btw, I know it's a bit knobbish and adds lots of noise to the PR, so probably best just to look at the individual commits.

I also added the copyright notice into the unminified source so that I could run `uglifyjs client.js -cm --comments "/Socket IO File Upload/" > client.min.js ` each time. Hopefully that's okay.

I also noticed for some reason that if I tried to use `var uintArr = new Uint8Array(content, start, end);` rather than `var uintArr = new Uint8Array(content);` it completely broke- no idea why though.

Here's the test code I was using:

## Client

```html
<script type='text/javascript' src='/socket.io/socket.io.js'></script>
<script type='text/javascript' src='/siofu/client.js'></script>

<input type='file' id='siofu_input'>
<div id='progress'></div>

<script type='text/javascript'>
  var socket = io.connect();
  var uploader = new SocketIOFileUpload(socket);

  uploader.chunkSize = 5120 * 100;
  uploader.listenOnInput(document.getElementById("siofu_input"));

  socket.on('file:event', function (e) {
    console.log(e.message);
    document.getElementById('progress').innerHTML = e.message;
  });
</script>
```

## Server:

```coffeescript
app = require('express')()
server = require('http').Server(app)
io = require('socket.io')(server)

siofu = require 'socketio-file-upload'

app.use siofu.router

app.get '/', (req, res) ->
  res.sendFile __dirname + '/index.html'

server.listen 8000, () ->
  console.log 'listening on 8000'

io.on 'connection', (socket) ->
  uploader = new siofu()
  uploader.dir = '/tmp'
  uploader.listen socket

  uploader.on 'start', (e) ->
    socket.emit 'file:event', {message: "Started: #{e.file.size} bytes to go"}

  uploader.on 'saved', (e) ->
    socket.emit 'file:event', {message: "Saved!"}

  uploader.on 'progress', (e) ->
    perc = Math.round e.file.bytesLoaded / e.file.size * 100
    socket.emit 'file:event', {message: "Uploaded: #{perc}%"}


  # You can also deal with each progress part, for example using streams:

  outputStream = null

  uploader.on 'start', (e) ->
    outputStream = require('fs').createWriteStream "/tmp/str_#{e.file.name}"
  uploader.on 'progress', (e) ->
    outputStream.write e.buffer
  uploader.on 'saved', (e) ->
    outputStream.end()
```

### CODE REVIEW

**Comment by vote539** [comment]
These changes have been merged into master.  I reverted the source back to tab indentation to make changes easier to see.  I split the rest of the contribution into two commits, 8fb80d1 for the style changes and 9b4fd10 for the functional changes.  Sorry for taking so long to merge this PR, and thanks for the contributions :smiley:

**Comment by MaffooBristol** [comment]
Brilliant! :smile: Yeah the style changes were because I kinda get blind to how the code works if it isn't how I'm used to seeing the formatting, but because it's very subjective and it is your module after all, really I should have just applied my changes over the original formatting, so sorry once again.

But yes, if I find any other things to contribute in the future I'll hopefully be able to do some more stuff. Cheers for merging :+1:

**Comment by vote539** [comment]
Version 0.4.0 has been published to npm.

I made a few refactoring changes to your code.  The main change is that you were allocating a new FileReader instance for every chunk, but that does not seem to be necessary.  I changed it to reuse the same instance for every chunk.

Thanks again :smiley_cat:

**Comment by ArtskydJ** [comment]
Does this close #3?

**Comment by vote539** [comment]
It closes #7 actually.

**Comment by vote539** [comment]
And yes, it also closes #3. 😆

**Pull request closed without merging**
